before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    id: "lnet"
    binary: "lnet"
    goos:
      - linux
      - darwin
    goarch:
      - "amd64"
      - "arm"
      - "arm64"
      - "386"
    ldflags:
      - -s -w -X 'github.com/louislef299/lnet/pkg/version.Version={{.Version}}'
      - -X 'github.com/louislef299/lnet/pkg/version.BuildOS={{.Runtime.Goos}}'
      - -X 'github.com/louislef299/lnet/pkg/version.BuildArch={{.Runtime.Goarch}}'
      - -X 'github.com/louislef299/lnet/pkg/version.GoVersion={{.Env.GOVERSION}}'
      - -X 'github.com/louislef299/lnet/pkg/version.BuildTime={{.Date}}'
      - -X 'github.com/louislef299/lnet/pkg/version.CommitHash={{.ShortCommit}}'
archives:
  - builds:
    - lnet
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    id: lnet
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
- name: lnet
  commit_author:
    name: Louis Lefebvre
    email: louislefebvre1999@gmail.com
  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
  homepage: "https://github.com/louislef299/lnet"
  repository:
    owner: louislef299
    name: homebrew-lnet
    branch: main
    token: "{{ .Env.GITHUB_TOKEN }}"
