---
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - name: release
      uses: google-github-actions/release-please-action@v3
      with:
        prerelease: true
        release-type: simple
        skip-github-release: true
        version-file: version.txt
    - uses: actions/checkout@v3
    - run: |
        echo "Github event: ${{ github.event_name }}"
    - name: tag release versions
      if: ${{ steps.release.outputs.release_created }} # ${{ github.event_name }} == "push"
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/louislef299/lnet.git"
        git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}".${{ steps.release.outputs.patch }}
        git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}

name: Release Please
'on':
  push:
    branches:
    - main

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write