---
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        prerelease: true
        release-type: simple
        skip-github-release: true
        version-file: version.txt

name: Release Please
'on':
  push:
    branches:
    - main

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write