---
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/release-please-action@v3
      with:
        prerelease: true
        release-type: go
        token: ${{ secrets.RELEASE_PLEASE_PAT }}
        version-file: version.txt

name: Release Please
'on':
  push:
    branches:
    - main