---
env:
  GOVERSION: "1.20.0"

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
    - id: release
      uses: google-github-actions/release-please-action@v3
      with:
        prerelease: true
        release-type: simple
        version-file: version.txt
    - run: |
        echo "release created: ${{ steps.release.outputs.releases_created }}"

  go-release:
    if: ${{ needs.release-please.outputs.release_created }}
    needs: release-please
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: git fetch --force --tags
    - uses: actions/setup-go@v4
      with:
        go-version: '>=${{ env.GOVERSION }}'
    - uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Release Please
'on':
  push:
    branches:
    - main

permissions:
  contents: write
  issues: write
  packages: write
  pull-requests: write